// ---------------------------------------------------------------------------
// FRR Manager — Configuration Generation & Service Lifecycle
// ---------------------------------------------------------------------------
// Generates FRR configuration from ATLAS's BGP settings, writes it to disk,
// and manages the bgpd service lifecycle (start, stop, restart).
//
// ATLAS owns the FRR config entirely — it writes a complete frr.conf based
// on atlas.config.json's bgp section. This means any manual FRR edits will
// be overwritten on the next config push.
//
// FRR components used:
//   - bgpd only (no zebra, ospfd, isisd, etc.)
//   - Northbound gRPC enabled for ATLAS ↔ FRR communication
//   - VPNv4 unicast + BGP-LS address families
//
// Config flow:
//   atlas.config.json → frrManager.generate() → /etc/frr/frr.conf → restart
// ---------------------------------------------------------------------------

const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', '..', 'atlas.config.json');

// Default paths — overridable via atlas.config.json bgp.frr section
const DEFAULTS = {
  configPath: '/etc/frr/frr.conf',
  daemonsPath: '/etc/frr/daemons',
  restartCommand: 'rc-service frr restart',
  statusCommand: 'rc-service frr status',
  grpcPort: 50051,
};

/**
 * Read the current BGP config from atlas.config.json.
 * @returns {Object} The bgp config block, or empty defaults.
 */
function readBgpConfig() {
  try {
    const raw = fs.readFileSync(CONFIG_PATH, 'utf-8');
    const config = JSON.parse(raw);
    return config.bgp || {};
  } catch {
    return {};
  }
}

/**
 * Write updated BGP config back to atlas.config.json.
 * Merges with existing config — does not touch polling/devices.
 * @param {Object} bgpConfig - The full bgp config block.
 */
function writeBgpConfig(bgpConfig) {
  try {
    const raw = fs.readFileSync(CONFIG_PATH, 'utf-8');
    const config = JSON.parse(raw);
    config.bgp = bgpConfig;
    fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  } catch (err) {
    throw new Error(`Failed to write BGP config: ${err.message}`);
  }
}

/**
 * Generate the FRR daemons file content.
 * Enables only bgpd with gRPC northbound support.
 * @param {Object} bgpConfig - The bgp config block.
 * @returns {string} daemons file content.
 */
function generateDaemons(bgpConfig) {
  const frr = bgpConfig.frr || {};
  const grpcPort = frr.grpcPort || DEFAULTS.grpcPort;
  const grpcEnabled = frr.grpcEnabled || false;

  // bgpd options: only add gRPC module if explicitly enabled
  // Alpine's FRR package does not include gRPC support
  const bgpdOpts = grpcEnabled
    ? `bgpd_options="  -A 127.0.0.1 -M grpc:${grpcPort}"`
    : `bgpd_options="  -A 127.0.0.1"`;

  return `# Generated by ATLAS — do not edit manually
#
# FRR Daemons Configuration
# Only bgpd is enabled — ATLAS uses FRR as a BGP-only collector.
# zebra is required as it handles interface and routing table integration.

zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no

#
# Daemon options
#
${bgpdOpts}

#
# Global FRR options
#
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
`;
}

/**
 * Generate the FRR configuration file content from ATLAS BGP settings.
 *
 * Produces a complete frr.conf with:
 *   - BGP router config (ASN, router-id)
 *   - Peer-group definition for route reflector sessions
 *   - Per-neighbor config under the peer-group
 *   - Address-family activation (VPNv4, BGP-LS)
 *   - Soft-reconfiguration inbound for full RIB visibility
 *
 * @param {Object} bgpConfig - The bgp config block from atlas.config.json.
 * @returns {string} Complete frr.conf content.
 */
function generateFrrConf(bgpConfig) {
  const localAs = bgpConfig.localAs || 65000;
  const routerId = bgpConfig.routerId || '0.0.0.0';
  const sourceAddress = bgpConfig.sourceAddress || routerId;
  const neighbors = bgpConfig.neighbors || [];
  const afis = bgpConfig.addressFamilies || {};

  let conf = `! Generated by ATLAS — do not edit manually
! Configuration is managed via the ATLAS BGP settings UI.
!
frr defaults traditional
hostname atlas-bgp
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp ${localAs}
 bgp router-id ${routerId}
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 !
 ! Peer-group for Route Reflector sessions
 ! update-source: ${sourceAddress}${sourceAddress !== routerId ? ` (router-id: ${routerId})` : ''}
 neighbor ATLAS-RR peer-group
 neighbor ATLAS-RR remote-as ${localAs}
 neighbor ATLAS-RR update-source ${sourceAddress}
 neighbor ATLAS-RR timers 10 30
`;

  // Per-neighbor configuration
  for (const nbr of neighbors) {
    conf += ` !
 neighbor ${nbr.address} peer-group ATLAS-RR
`;
    if (nbr.description) {
      conf += ` neighbor ${nbr.address} description ${nbr.description}
`;
    }
  }

  // VPNv4 address family
  if (afis.vpnv4?.enabled !== false) {
    conf += ` !
 address-family ipv4 vpn
  neighbor ATLAS-RR activate
  neighbor ATLAS-RR soft-reconfiguration inbound
 exit-address-family
`;
  }

  // BGP-LS address family
  if (afis.bgpLs?.enabled !== false) {
    conf += ` !
 address-family link-state link-state
  neighbor ATLAS-RR activate
 exit-address-family
`;
  }

  conf += `exit
!
end
`;

  return conf;
}

/**
 * Write the FRR configuration files to disk.
 * @param {Object} bgpConfig - The bgp config block.
 * @returns {{ confPath: string, daemonsPath: string }} Written file paths.
 */
function writeConfFiles(bgpConfig) {
  const frr = bgpConfig.frr || {};
  const confPath = frr.configPath || DEFAULTS.configPath;
  const daemonsPath = frr.daemonsPath || DEFAULTS.daemonsPath;

  const confContent = generateFrrConf(bgpConfig);
  const daemonsContent = generateDaemons(bgpConfig);

  fs.writeFileSync(confPath, confContent, 'utf-8');
  console.log(`  [FRR] Wrote ${confPath}`);

  fs.writeFileSync(daemonsPath, daemonsContent, 'utf-8');
  console.log(`  [FRR] Wrote ${daemonsPath}`);

  return { confPath, daemonsPath };
}

/**
 * Restart the FRR service.
 * @param {Object} bgpConfig - The bgp config block (for restart command override).
 * @returns {{ success: boolean, output: string }}
 */
function restartService(bgpConfig) {
  const frr = bgpConfig.frr || {};
  const cmd = frr.restartCommand || DEFAULTS.restartCommand;

  try {
    const output = execSync(cmd, { encoding: 'utf-8', timeout: 30000 });
    console.log(`  [FRR] Service restarted successfully`);
    return { success: true, output: output.trim() };
  } catch (err) {
    console.error(`  [FRR] Restart failed:`, err.message);
    return { success: false, output: err.message };
  }
}

/**
 * Check if FRR service is running.
 * @param {Object} bgpConfig - The bgp config block.
 * @returns {{ running: boolean, status: string }}
 */
function getServiceStatus(bgpConfig) {
  const frr = bgpConfig.frr || {};
  const cmd = frr.statusCommand || DEFAULTS.statusCommand;

  try {
    const output = execSync(cmd, { encoding: 'utf-8', timeout: 10000 });
    const status = output.trim();
    // systemd returns "active", OpenRC includes "started" in output
    const running = status === 'active' || status.includes('started');
    return { running, status };
  } catch {
    return { running: false, status: 'inactive' };
  }
}

/**
 * Full deploy: save config → write FRR files → restart service.
 * This is the main entry point called from the API route.
 *
 * Each step is attempted independently so partial failures are reported
 * clearly (e.g., config saved but FRR not installed yet).
 *
 * @param {Object} bgpConfig - The complete bgp config block.
 * @returns {{ success: boolean, configSaved: boolean, filesWritten: boolean, restart: Object|null, error: string|null }}
 */
function deploy(bgpConfig) {
  const result = {
    success: false,
    configSaved: false,
    filesWritten: false,
    restart: null,
    error: null,
  };

  // 1. Save to atlas.config.json (always succeeds or throws to caller)
  writeBgpConfig(bgpConfig);
  result.configSaved = true;

  // 2. Generate and write FRR config files
  try {
    writeConfFiles(bgpConfig);
    result.filesWritten = true;
  } catch (err) {
    result.error = `Config saved, but failed to write FRR files: ${err.message}. Is FRR installed?`;
    return result;
  }

  // 3. Restart FRR
  const restart = restartService(bgpConfig);
  result.restart = restart;
  result.success = restart.success;

  if (!restart.success) {
    result.error = `Config saved and FRR files written, but service restart failed: ${restart.output}`;
  }

  return result;
}

/**
 * Generate a preview of the FRR config without writing or restarting.
 * Useful for the UI to show what will be deployed.
 *
 * @param {Object} bgpConfig - The bgp config block.
 * @returns {{ frrConf: string, daemons: string }}
 */
function preview(bgpConfig) {
  return {
    frrConf: generateFrrConf(bgpConfig),
    daemons: generateDaemons(bgpConfig),
  };
}

module.exports = {
  readBgpConfig,
  writeBgpConfig,
  generateFrrConf,
  generateDaemons,
  writeConfFiles,
  restartService,
  getServiceStatus,
  deploy,
  preview,
  DEFAULTS,
};
